config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount VideoUploader::UploadEndpoint, at: '/attachments/videos'

  root 'welcome#index'

  devise_for :users, controllers: { registrations: "registrations" }

  resources :topics do
    resources :posts
  end
  
  resources :posts, only: [:show, :index]
  resources :profiles

  resources :posts do 
    member do
      get "next", to: "posts#next"
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end 

  post "/webhooks/transloadit" do
    Shrine::Attacher.transloadit_save(params)
  end

  get 'welcome', :to => 'welcome#index'
  get 'about', :to => 'welcome#about'
  get 'conditions', :to => 'welcome#conditions'

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_server_error"

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts
  belongs_to :user
  accepts_nested_attributes_for :posts

  validates :title, presence: true
  validates :description, presence: true
  validates :location, presence: true

  include ImageUploader[:image] # adds an `image` virtual attribute

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: %i[new create update]
  # before_action :authenticate_admin!, only: %i[new create update]
  # before_filter :authenticate_any!, only: %i[new create update]

  def index
    @topics = Topic.all
  end

  def show
  end

  def new
    @topic = Topic.new
  end

  def edit
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user
    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_topic
      @topic = Topic.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:user_id, :title, :description, :location, :wikipedia, :image, :remove_image, :deadline, :active)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper

end

app/views/topics/_form.html.erb
<%= simple_form_for @topic do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
   
    <%= f.input :title %>
    
    <div class="pull-right"><span id="body-count">250</span> characters left</div>
    
    <%= f.input :description, input_html: { :id => "body-field", :cols => 5, :rows => 3 } %>
    
    <%= f.input :location, as: :country %>
    
    <%# f.input :image, as: :file, :input_html => {:onchange => "previewFile()"} %>

<!--     <div style="text-align:center">
      <img height="100%" width="60%" alt="Image preview...">
    </div>
 -->
  </div>
  <hr>

  <%= f.submit :submit, class:'btn btn-flat flat-inverse btn-rounded btn-block' %>

<% end %>

<script type="text/javascript">
$(document).ready(function() {
  $("#body-field").on("keyup", function(){
    var length = $(this).val().length;
    $("#body-count").html(250 - length);
  });
});
</script>

app/views/topics/_topic.html.erb
<div class="panel" style="border-radius:4px;box-shadow:0 10px 16px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19) !important">
  <div class="panel-body center">
    <div class="row">    
      <div class="col-sm-12">
        <h3><%= topic.title %></h3>  
        <%# if topic.deadline.future? %>
        <!-- <h5 style="color:#95a5a6"><%# topic.deadline.strftime("%d %B %Y") %></h5> -->
        <%# else %>
        <!-- <h5 style="color:#95a5a6">No date set</h5> -->
        <%# end %>
        <hr style="margin:5px">
        <p><%= simple_format(topic.description) %></p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
      <% if owner(topic) || current_admin.present? %>
        <%= link_to 'EDIT', edit_topic_path(topic), class:'btn btn-flat flat-inverse btn-rounded btn-md' %>
        <br><br>
      <% end %>
      <%= link_to 'ADD NEW VIDEO', new_topic_post_path(topic), class:'btn btn-flat flat-success btn-rounded btn-md' %>
      </div>
    </div>

  </div>
</div>

app/views/topics/_topic_panel.html.erb
<div class="col-md-6 center" >

  <div class="panel panel-default" style="border-radius:4px;box-shadow:0 10px 16px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19) !important;">
    <div class="panel-body">

      <%# image_tag("#{topic.picture}", style:'width:100%;height:170px;margin-bottom:10px;opacity:0.8;') %>
      <h5><%= topic.title %></h5>
      <hr>
      <%= link_to 'BROWSE VIDEOS', topic_posts_path(topic), class:'btn btn-flat flat-info btn-rounded btn-sm', style:'margin:5px' %>
      <%= link_to 'ADD VIDEO', new_topic_post_path(topic), class:'btn btn-flat flat-success btn-rounded btn-sm', style:'margin:5px' %>
      <br>
      <h6>Videos:  <%= topic.posts.published.count %></h6>

    </div>
    
  </div>

</div>

app/views/topics/edit.html.erb
<div class="col-lg-4 col-lg-offset-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Editing Topic</h3>
    </div>
    <div class="panel-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="container">
  <div class="row"> 
    <div class="col-sm-10 col-sm-offset-1 col-xs-12">

      <div class="panel panel-default">
        <div class="panel-heading center">
          <h3>Current Topics</h3>
        </div>
        <div class="panel-body">
          <table class="table">
            <thead>
              <tr>
                <th><h5>#</h5></th>
                <th><h5>Title</h5></th>
                <th class="hidden-xs"><h5>Location</h5></th>
                <th class="hidden-xs"><h5>Videos</h5></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @topics.each_with_index do |topic, index| %>
                <%= link_to topic_posts_path(topic) do %>
                <tr>
                  <td><%= index + 1 %></td>
                  <td><%= topic.title %></td>
                  <td class="hidden-xs"><%= topic.location %></td>
                  <td class="hidden-xs"><%= topic.posts.count %></td>
                  <td><%= link_to 'View', topic_posts_path(topic) %></td>
                </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>

    </div>
  </div>

<br>
  <% if current_user.present? %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= link_to 'ADD NEW TOPIC', new_topic_path, class:'btn btn-flat flat-inverse btn-rounded btn-block' %>
    </div>
  </div>
<% end %>

</div>

app/views/topics/new.html.erb
<div class="col-lg-4 col-lg-offset-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>New Topic</h3>
    </div>
    <div class="panel-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= render partial: "topic", object: @topic, as: 'topic' %>
    </div>    
  </div>
  <div class="row">
  
  <% @topic.posts.published.each do |post| %>
    <%= link_to post do %>
      <%= render partial: '/posts/post', object: post %>
    <% end %>
  <% end %>

  </div>
</div>