config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount VideoUploader::UploadEndpoint, at: '/attachments/videos'

  root 'welcome#index'

  devise_for :users, controllers: { registrations: "registrations" }

  resources :topics do
    resources :posts
  end
  
  resources :posts, only: [:show, :index]
  resources :profiles

  resources :posts do 
    member do
      get "next", to: "posts#next"
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end 

  post "/webhooks/transloadit" do
    Shrine::Attacher.transloadit_save(params)
  end

  get 'welcome', :to => 'welcome#index'
  get 'about', :to => 'welcome#about'
  get 'conditions', :to => 'welcome#conditions'

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_server_error"

end

app/views/shared/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-md-offset-3 col-lg-offset-3 col-lg-6 col-md-6 center">
      <ul class="list-inline" style="font-weight:900">
        <hr>
        <li>
          <%= link_to "https://www.facebook.com/VotersMinute/", target: "blank" do %>
            <i class="fa fa-facebook-official fa-2x" aria-hidden="true"></i>
          <% end %>
        </li>
        <li>
          <%= link_to "https://twitter.com/VotersMinute", target: "blank" do %>
            <i class="fa fa-twitter-square fa-2x" aria-hidden="true"></i>
          <% end %>
        </li>
        <li>
          <%= link_to "http://www.instagram.com", target: "blank" do %>
            <i class="fa fa-instagram fa-2x" aria-hidden="true"></i>
          <% end %>
        </li>
        <br>
        <br>
        <li><%= link_to "About", about_path %></li>
        <li><%= mail_to "contact@votersminute.com", "Request", subject: "Topic Request:" %></li>
        <li><%= link_to "Conditions", conditions_path %></li>
        <li><%= mail_to "contact@votersminute.com", "Contact", subject: "Contact:" %></li>
        <li><p>Copyright &copy; VotersMinute Ltd 2016</p></li>
      </ul>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<header class="header">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class:"navbar-brand" do %>Voters'<span> Minute</span>
        <% end %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>

          <li><%= link_to 'Videos', posts_path %></li>
          <li><%= link_to 'Topics', topics_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account  
              <i class="fa fa-caret-down" aria-hidden="true"></i>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Profile', profile_path(current_user.profile) %></li>
              <li><%= link_to 'Add Video', topics_path %></li>
              <li><%= link_to 'Settings', edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to destroy_user_session_path, method: :delete do %>Sign Out<% end %></li>
            </ul>
          </li> 

        <% elsif admin_signed_in? %>
          <li><%= link_to 'USERS', profiles_path %></li>
          <li><%= link_to 'VIDEOS', posts_path %></li>
          <li><%= link_to 'TOPICS', topics_path %></li>
          <li role="separator" class="divider"></li>

          <li><%= link_to destroy_user_session_path, method: :delete do %>SIGN OUT<% end %></li>

        <% else  %>

          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Videos', posts_path %></li>
          <li><%= link_to 'Topics', topics_path %></li>
          <li><%= link_to 'About', about_path %></li>

        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>