config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount VideoUploader::UploadEndpoint, at: '/attachments/videos'

  root 'welcome#index'

  devise_for :users, controllers: { registrations: "registrations" }

  resources :topics do
    resources :posts
  end
  
  resources :posts, only: [:show, :index]
  resources :profiles

  resources :posts do 
    member do
      get "next", to: "posts#next"
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end 

  post "/webhooks/transloadit" do
    Shrine::Attacher.transloadit_save(params)
  end

  get 'welcome', :to => 'welcome#index'
  get 'about', :to => 'welcome#about'
  get 'conditions', :to => 'welcome#conditions'

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_server_error"

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic

  acts_as_votable

  include VideoUploader[:video]

  after_update :processing_completed
  after_update :publish_latest_video

  scope :published, -> { where(live: true) }

  # Need to create method that checks whether the processing has been completed on video.  
  # The object will UPDATE once transcoding is complete, so a validation on UPDATE may work.
  # Need to check the video_data has been attached and then whether the screenshot string is present.

  def processing_completed
    if self.video_data.include? "screenshot"
      self.update_column(:processed, true)
    else
      self.update_column(:processed, false)
    end
  end

  def publish_latest_video
    other_videos_on_topic = user.posts.where(topic_id: topic.id).where.not(id: self)
    if other_videos_on_topic.count > 0
      other_videos_on_topic.update_all(live: false)
    end
    self.update_column(:live, true) if self.processed == true
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_topic, only: [:new, :create, :index, :edit, :update, :next, :upvote, :downvote]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :next, :upvote, :downvote]
  before_action :authenticate_user!, only: %i[new create upvote downvote]
  respond_to :html, :xml, :json

  def index
    if @topic.present?
      @posts = @topic.posts.published
    else
      @posts = Post.published
    end

  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.topic = @topic
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Your video has been uploaded but we need to process it, this may take a few minutes.' }
        format.json { render action: 'show', :id => @post.id, notice: 'Your video has been uploaded but we need to process it, this may take a few minutes.'}
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to root_path, notice: 'Post updated but we need to process it.' }
        format.json { render action: 'show', :id => @post.id}
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def next
    next_post
  end

  def upvote
    @post.upvote_by current_user
    render action: 'show', :id => @post.id
  end

  def downvote
    @post.downvote_from current_user
    render action: 'show', :id => @post.id
  end


  private

    def set_topic
      @topic = Topic.find(params[:topic_id]) if params[:topic_id].present?
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def next_post
      topic_posts = @post.topic.posts
      @other = topic_posts.published.order("RANDOM()").reject { |p| p.id == set_post.id }
      if @other.count == 0
        redirect_to posts_path, notice: "There's only one video on this topic right now. Why not share us with your friends!" 
      else 
        @next = @other.first
        redirect_to @next
      end
    end

    def post_params
      params.require(:post).permit!
    end
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/posts/_buttons.html.erb
<div class="btn-group" role="group" style="margin-top:20px">

  <%= mail_to "contact@votersminute.com", subject: "Report Video - Video ID: #{@post.id}", class:'btn btn-flat flat-danger btn-rounded btn-md' do %><i class="fa fa-bell fa-2x" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="REPORT"></i><% end %>

  <%= link_to dislike_post_path(@post), method: :put, class:"btn btn-flat flat-warning btn-rounded btn-md", "type" => "submit", "title" => "Disagree"  do %>
    <i class="fa fa-thumbs-down fa-2x" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="DISAGREE"></i>
  <% end %>
              
  <%= link_to like_post_path(@post), method: :put, class:"btn btn-flat flat-success btn-rounded btn-md", "type" => "submit", "title" => "Agree"  do %>
    <i class="fa fa-thumbs-up fa-2x" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="AGREE"></i>
  <% end %>

  <%= link_to next_post_path, class:'btn btn-flat flat-info btn-rounded btn-md' do %><i class="fa fa-arrow-right fa-2x" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="NEXT"></i><% end %>

</div>

app/views/posts/_form.html.erb
<h6 style="color:#2c3e50;font-weight:400;line-height:150%">

  We want people to add constructive arguments to the debate.  Not mindless, negative ranting. 
  <br><br>
  So before you record your video, think about what really matters to you and why it should matter to other people.
  <br><br>
  We'd prefer you didn't swear or say anything to deliberately offend or provoke others.
  <br><br>
  This may be your chance to change someones' mind, so make your minute count.
  <br>
</h6>
  <hr>
<div id="url" data-posturl="<%= topic_posts_path(@topic, @post) %>">

  <div class="form-group-uploader">
    <label>Select Video</label>
    <%= file_field_tag :file, multiple: true %>
    <br>
  </div>

</div>

app/views/posts/_post.html.erb
<div class="post_partial col-lg-3 col-md-4 col-sm-6 col-xs-12">
  <%= link_to post do %>
    <% if post.video.present? %>
        <% if post.processed %>

        <div class="hovereffect" style="box-shadow:0 10px 16px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19) !important;">
          <%= image_tag(post.video_url(:screenshot), style:"width:100%;height:250px;border-radius:2px;") %>

          <div class="overlay">
            <h6><%= post.topic.title %></h6>
          </div>

        </div>
        
        <% else %>

        <div style="width:100%;height:290px;border-radius:2px">
          
          <div class="hovereffect">
            <div class="loader"></div>
            <h5>Processing video</h5>
          </div>

        </div>
        <% end %>

    <% else %>

      <h4><%= post.topic.title %></h4>
      <p><%= post.id %></p>

      <h6>Live:</h6>
      <p><%= post.live %></p>

      <h6>Share:</h6>
      <p><%= post.share %></p>

    <% end %>
  <% end %>

    <% if owner(post) %>
        <% link_to 'Edit', edit_topic_post_path(post.topic, post) %> 
        <% link_to 'Back', topic_path(post.topic) %>
    <% end %>

  </div>

app/views/posts/_video.html.erb
<% content_for :head do %>
  <!-- Schema.org markup for Google+ -->
  <meta itemprop="name" content="Voters' Minute">
  <meta itemprop="description" content="Share your opinion.
Whether it's an election or a referendum, everyone's opinion matters.
Voters' Minute is a simple way to share your opinion.
Pick an issue, record your video and upload it.">
  <!-- <meta itemprop="image" content="http://www.example.com/image.jpg"> -->

  <!-- Twitter Card data -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="Voters Minute">
  <meta name="twitter:title" content="<%= @post.topic.title %>">
  <meta name="twitter:description" content="#myminute #votersminute">
  <!-- Twitter summary card with large image must be at least 280x150px -->
  <meta name="twitter:image:src" content="<%= @post.video_url(:screenshot) %>">

  <!-- Open Graph data -->
  <meta property="og:title" content="Voters Minute" />
  <meta property="og:video" content="<%= @post.video_url(:video) %>" />
  <meta property="og:url" content="<%= request.original_url %>" />
  <meta property="og:image" content="<%= @post.video_url(:screenshot) %>" />
  <meta property="og:description" content="<%= @post.topic.title %>" />
  <meta property="og:site_name" content="Voters Minute" />
  <meta property="fb:admins" content="Facebook numberic ID" />
<% end %>

<div class="container">
  <div class="row">

    <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
      <div class="panel" style="text-align:center;border-radius:4px;box-shadow:0 10px 16px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19) !important;">
        <div class="panel-body">

        <h5><%= video.topic.title %></h5>
        <br>
          <% if video.processed %>

            <%= video_tag(video.video_url(:video), controls: true, autobuffer: true, style:"width:100%;height:100%;max-height:350px") %>

          <% else %>
            <h4>Video <%= video.id %> still being processed</h4>
            <br>
          <% end %>

          <%= render partial: '/posts/buttons', locals: { video: @post } %>


          <% if video.user.profile.share == true %>
            <hr>
            <div class="addthis_inline_share_toolbox" style="margin:10px"></div>
          <% end %>

        </div>
      </div>
    </div>

  </div>
</div>


<script type="text/javascript">

  $('#example').tooltip(options)

</script>

app/views/posts/edit.html.erb
<div class="col-lg-4 col-lg-offset-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Editing Post</h3>
    </div>
    <div class="panel-body">
      <%= render 'form' %>
      <%= link_to 'Show', topic_post_path(@post, @topic) %> | <%= link_to 'Back', topic_posts_path %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row"> 

    <div class="col-sm-12">
      <% if @topic.present? %>

      <%= render partial: '/topics/topic', object: @topic, as: 'topic' %>

      <% end %>
    </div>
  </div>
  <br>
  <div class="row">
    <div id="postList">
      <% @posts.order(:cached_weighted_average => :asc).each do |post| %>

      <div class="item <%= post.topic.id %>">

        <%= render partial: "/posts/post", object: post, as: 'post' %>
      
      </div>

      <% end %>

    </div>

  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <% if @topic.present? %>
        <%= link_to 'ADD NEW VIDEO', new_topic_post_path(@topic), class:'btn btn-flat flat-success btn-rounded btn-block' %>
      <% else %>
        <%= link_to 'ADD NEW VIDEO', topics_path, class:'btn btn-flat flat-success btn-rounded btn-block' %>
      <% end %>
    </div>
  </div>


</div>

<script type="text/javascript">
  
$(document).ready(function() {
  $('#topicFilterOptions h6 a').hover(function() {
    // fetch the class of the clicked item
    var ourClass = $(this).attr('class');

    // reset the active class on all the buttons
    $('#topicFilterOptions h6').removeClass('active');
    // update the active state on our clicked button
    $(this).parent().addClass('active');

    if(ourClass == 'all') {
      // show all our items
      $('#postList').children('div.item').show();
    }
    else {
      // hide all elements that don't share ourClass
      $('#postList').children('div:not(.' + ourClass + ')').hide();
      // show all elements that do share ourClass
      $('#postList').children('div.' + ourClass).show();
    }
    return false;
  });
});

</script>

app/views/posts/new.html.erb
<div class="col-lg-4 col-lg-offset-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="center">Add Video</h3>
      <h5 class="center" style="color:#95a5a6"><%= @topic.title %></h5>
    </div>
    <div class="panel-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/posts/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/posts/show.html.erb
<%= render partial: '/posts/video', locals: { video: @post } %>